Add rules_go and Gazelle which seem to be required by bazel-toolchains now.
Fixes this error that happens otherwise when bumping bazel-toolchains:

ERROR: /workdir/src/BUILD:743:10: error loading package '@bazel_toolchains//': Unable to find package for @bazel_gazelle//:def.bzl: The repository '@bazel_gazelle' could not be resolved. and referenced by '//src:test_repos'